# Generated by Django 4.1.5 on 2023-01-11 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCodes',
            fields=[
                ('zip_code', models.CharField(editable=False, max_length=5, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'zip_codes',
            },
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('ZoneID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('LatitudeMin', models.FloatField()),
                ('LatitudeMax', models.FloatField()),
                ('NorthSouth', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Zones',
            },
        ),
        migrations.CreateModel(
            name='SunshineAvailability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Month', models.IntegerField()),
                (' Strength', models.IntegerField()),
                ('ZoneId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zones')),
            ],
            options={
                'db_table': 'Sunshine_Availability',
            },
        ),
    ]
