# Generated by Django 4.1.5 on 2023-01-10 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('ZoneID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('LatitudeMin', models.FloatField()),
                ('LatitudeMax', models.FloatField()),
                ('NorthSouth', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='VitaminStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.IntegerField()),
                ('Strength', models.IntegerField()),
                ('zones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zones')),
            ],
        ),
    ]
