# Generated by Django 4.1.5 on 2023-01-12 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCodes',
            fields=[
                ('zip_code', models.CharField(editable=False, max_length=5, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'zip_codes',
            },
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('ZoneID', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('LatitudeMin', models.FloatField()),
                ('LatitudeMax', models.FloatField()),
                ('NorthSouth', models.CharField(max_length=1)),
                ('vitamin_type', models.IntegerField(choices=[(1, 'Vitamin_A'), (2, 'Vitamin_B'), (3, 'Vitamin_C'), (4, 'Vitamin_D')], default=1)),
            ],
            options={
                'db_table': 'Zones',
            },
        ),
        migrations.CreateModel(
            name='SunshineAvailability',
            fields=[
                ('SunshineId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Month', models.IntegerField()),
                ('Strength', models.IntegerField()),
                ('vitamin_type', models.IntegerField(choices=[(1, 'Vitamin_A'), (2, 'Vitamin_B'), (3, 'Vitamin_C'), (4, 'Vitamin_D')], default=1, null=True)),
                ('ZoneID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strengths', to='app.zones')),
            ],
            options={
                'db_table': 'Sunshine_Availability',
            },
        ),
    ]
