# Generated by Django 4.1.5 on 2023-01-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitaminstrength',
            old_name='zones',
            new_name='Zone',
        ),
    ]
