# Generated by Django 4.1.5 on 2023-01-11 05:43

from django.db import migrations


class Migration(migrations.Migration):
    def initiateData(self,schema_editor):
        import pandas as pd
        from django.conf import settings
        from sqlalchemy import create_engine

        xls = pd.ExcelFile('app/data/Vitamin D (1).xlsx')
        df1 = pd.read_excel(xls, 'Vitamin D Strength')
        df2 = pd.read_excel(xls, 'Zones')
        df1.columns = ["ZoneID_id", "Month", "Strength"]
        df2.columns = ["ZoneID", "LatitudeMin", "LatitudeMax", "NorthSouth"]
        df2.set_index("ZoneID", inplace=True)
        user = settings.DATABASES['default']['USER']
        password = settings.DATABASES['default']['PASSWORD']
        database_name = settings.DATABASES['default']['NAME']

        database_url = 'postgresql://root:root@localhost:5432/postgres'.format(
            user=user,
            password=password,
            database_name=database_name,
        )
        engine = create_engine(database_url, echo=False)

        df1.to_sql('Sunshine_Availability', con=engine, if_exists='replace')
        df2.to_sql('Zones', con=engine, if_exists='replace')

    dependencies = [
        ('app', '0002_auto_20230111_0542'),
    ]

    operations = [
        migrations.RunPython(initiateData)
    ]
