# Generated by Django 4.1.5 on 2023-01-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_zones_vitaminstrength_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitaminstrength',
            old_name='Zone',
            new_name='ZoneID',
        ),
    ]
