# Generated by Django 4.1.5 on 2023-01-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_zone_vitaminstrength_zoneid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitaminstrength',
            old_name='ZoneID',
            new_name='Zone',
        ),
    ]
