# Generated by Django 3.2.12 on 2023-01-13 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230112_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sunshineavailability',
            old_name='ZoneID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='zones',
            old_name='ZoneID',
            new_name='id',
        ),
    ]
