# Generated by Django 4.1.5 on 2023-01-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230112_0957'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sunshineavailability',
            table='sunshine_availibilty',
        ),
        migrations.AlterModelTable(
            name='zones',
            table='zones',
        ),
    ]
