# Generated by Django 4.1.5 on 2023-01-11 11:52

from django.db import migrations


class Migration(migrations.Migration):
    def initiateData(self, schema_editor):

        from django.conf import settings
        from sqlalchemy import create_engine
        import pandas as pd
        from app.models import SunshineAvailability, Zones

        xls = pd.ExcelFile('app/data/Vitamin D (1).xlsx')
        df1 = pd.read_excel(xls, 'Vitamin D Strength')
        df2 = pd.read_excel(xls, 'Zones')
        for df1 in df1.itertuples():
            obj = SunshineAvailability.objects.create(ZoneID=df1.ZoneID,Month=df1.Month, Strength=df1.Strength)
            obj.save()

        for df2 in df2.itertuples():
            obj1 = Zones.objects.create(ZoneID=df2.ZoneID, LatitudeMin=df2.LatitudeMin, LatitudeMax=df2.LatitudeMax,
                                        NorthSouth=df2.NorthSouth)
            obj1.save()

    dependencies = [
        ('app', '0002_auto_20230111_1152'),
    ]

    operations = [
        migrations.RunPython(initiateData)
    ]
