# Generated by Django 4.1.5 on 2023-01-12 04:22

from django.db import migrations


class Migration(migrations.Migration):
    def initiateData(self, schema_editor):

        from django.conf import settings
        from sqlalchemy import create_engine
        import pandas as pd
        from app.models import SunshineAvailability, Zones
        xls = pd.ExcelFile('app/data/Vitamin D (1).xlsx')
        df1 = pd.read_excel(xls, 'Vitamin D Strength')
        df2 = pd.read_excel(xls, 'Zones')

        for df2 in df2.itertuples():
            obj1 = Zones.objects.create(ZoneID=df2.id, LatitudeMin=df2.LatitudeMin, LatitudeMax=df2.LatitudeMax,
                                        NorthSouth=df2.NorthSouth)
            obj1.save()

        for df1 in df1.itertuples():
            zones = Zones.objects.get(ZoneID=df1.id)
            obj = SunshineAvailability(ZoneID=zones,Month=df1.Month, Strength=df1.Strength)
            obj.save()

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initiateData)
    ]
