# Generated by Django 4.1.5 on 2023-01-11 11:07

from django.db import migrations


class Migration(migrations.Migration):
    def initiateData(self, schema_editor):

        from django.conf import settings
        from sqlalchemy import create_engine
        import pandas as pd
        from app.models import SunshineAvailability,Zones

        xls = pd.ExcelFile('app/data/Vitamin D (1).xlsx')
        df1 = pd.read_excel(xls, 'Vitamin D Strength')
        df2 = pd.read_excel(xls, 'Zones')
        df1.columns = ["zone_id", "Month", "Strength"]
        df2.columns = ["ZoneID", "LatitudeMin", "LatitudeMax", "NorthSouth"]
        df2.set_index("ZoneID", inplace=True)


        for df1 in df1.itertuples():
            obj = SunshineAvailability.objects.create(month=df1.Month, strength=df1.Strength,zone=df1.zone_id)
            obj.save()

        for df2 in df2.itertuples():
            obj1 = Zones.objects.create(zoneID=df1.ZoneID, latitudeMin=df1.LatitudeMin,latitudeMax=df1.LatitudeMax, northSouth=df1.NorthSouth)
            obj1.save()


        # user = settings.DATABASES['default']['USER']
        # password = settings.DATABASES['default']['PASSWORD']
        # database_name = settings.DATABASES['default']['NAME']
        #
        # database_url = 'postgresql://root:root@localhost:5432/postgres'.format(
        #     user=user,
        #     password=password,
        #     database_name=database_name,
        # )
        # engine = create_engine(database_url, echo=False)
        #
        # df1.to_sql('Sunshine_Availability', con=engine, if_exists='append',index=False)
        # df2.to_sql('Zones', con=engine, if_exists='append',index=False)
    dependencies = [
        ('app', '0002_auto_20230111_1107'),
    ]

    operations = [
        migrations.RunPython(initiateData)
    ]
